source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer'
end

gem 'jquery-rails'
gem 'bcrypt-ruby'
require 'bcrypt'

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'debugger'
end